import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomBytes} from 'node:crypto';
const base=process.env.TEST_URL||'http://127.0.0.1:8787';
const origin=new URL(base).origin;
const request=async (path,method='GET',body,session,requestOrigin=origin)=>{
 const res=await fetch(base+'/api'+path,{method,headers:{...(body!==undefined?{'Content-Type':'application/json'}:{}),...(method!=='GET'?{'Origin':requestOrigin}:{}),...(session?{'Cookie':session}:{})},body:body!==undefined?JSON.stringify(body):undefined});
 return {status:res.status,data:await res.json(),cookie:res.headers.get('set-cookie')?.split(';')[0]};
};
test('authentication, authorization, scores, sessions, bounded local traffic',async()=>{
 assert.equal((await request('/health')).status,200);
 assert.equal((await request('/teams')).status,401);
 assert.equal((await request('/users')).status,401);
 assert.equal((await request('/login','POST',{email:'a@b.com',password:'pass'},null,'https://evil.invalid')).status,403);
 const initialized=await request('/setup-status');
 assert.equal(initialized.status,200);
 // This test needs a clean local database so it cannot accidentally modify a real deployment.
 assert.equal(initialized.data.initialized,false,'Use a clean local D1 state for the integration test');
 const secret=process.env.TEST_BOOTSTRAP_SECRET;
 assert(secret && secret.length>=32,'Run through npm test to provide an isolated bootstrap secret');
 const adminPassword=randomBytes(24).toString('hex'),coachPassword=randomBytes(24).toString('hex');
 const adminEmail='administrator@test.invalid',coachEmail='coach@test.invalid';
 assert.equal((await request('/bootstrap','POST',{secret:'bad',email:adminEmail,name:'Admin',password:adminPassword})).status,403);
 assert.equal((await request('/bootstrap','POST',{secret,email:adminEmail,name:'Admin',password:adminPassword})).status,201);
 assert.equal((await request('/bootstrap','POST',{secret,email:'other@test.invalid',name:'Other',password:adminPassword})).status,409);
 assert.equal((await request('/bootstrap','POST',{secret,email:'other@test.invalid',name:'Other',password:adminPassword},null,'https://evil.invalid')).status,403);
 assert.equal((await request('/login','POST',{email:adminEmail,password:'wrong'})).status,401);
 const login=await request('/login','POST',{email:adminEmail,password:adminPassword});
 assert.equal(login.status,200);assert(login.cookie?.startsWith('gic_session='));
 const admin=login.cookie;
 assert.equal((await request('/users','POST',{name:'Coach',email:coachEmail,role:'coach',password:coachPassword},admin)).status,201);
 const coach=(await request('/login','POST',{email:coachEmail,password:coachPassword})).cookie;
 assert(coach);
 assert.equal((await request('/users','GET',undefined,coach)).status,403);
 assert.equal((await request('/audit','GET',undefined,coach)).status,403);
 assert.equal((await request('/users','POST',{name:'Evil',email:'evil@test.invalid',role:'admin',password:adminPassword},coach)).status,403);
 assert.equal((await request('/teams','POST',{name:'No origin',track:'Main Track',campus:'A',leader:'B'},admin,'https://evil.invalid')).status,403);
 assert.equal((await request('/teams','POST',{name:'Unauthorized',track:'Main Track',campus:'A',leader:'B'},coach)).status,403);
 assert.equal((await request('/teams','POST',{name:'Bad',track:'Main Track',campus:'A',leader:'B',deck_url:'javascript:alert(1)'},admin)).status,400);
 assert.equal((await request('/teams','POST',{name:'Bad',track:'Main Track',campus:'A',leader:'B',deck_url:'//evil.invalid'},admin)).status,400);
 assert.equal((await request('/teams','POST',{name:'Bad',track:'Main Track',campus:'A',leader:'B',deck_url:'https://example.invalid'},admin,'https://evil.invalid')).status,403);
 const created=await request('/teams','POST',{name:'Test team',track:'Main Track',campus:'Hyderabad',leader:'Student'},admin);
 assert.equal(created.status,201);const id=created.data.id;
 assert.equal((await request('/evaluations/'+id,'PUT',{score:101,feedback:'No'},coach)).status,400);
 assert.equal((await request('/evaluations/'+id,'PUT',{score:-1,feedback:'No'},coach)).status,400);
 assert.equal((await request('/evaluations/'+id,'PUT',{score:1.5,feedback:'No'},coach)).status,400);
 assert.equal((await request('/evaluations/'+id,'PUT',{score:1,feedback:'x'.repeat(3001)},coach)).status,400);
 const malformed=await fetch(base+'/api/evaluations/'+id,{method:'PUT',headers:{Origin:origin,'Content-Type':'application/json',Cookie:coach},body:'{broken'});
 assert.equal(malformed.status,400);
 const oversized=await fetch(base+'/api/evaluations/'+id,{method:'PUT',headers:{Origin:origin,'Content-Type':'application/json',Cookie:coach},body:JSON.stringify({score:1,feedback:'x'.repeat(17000)})});
 assert.equal(oversized.status,400);
 assert.equal((await request('/evaluations/'+id,'PUT',{score:85,feedback:'Promising'},coach)).status,200);
 assert.equal((await request('/evaluations/'+id,'PUT',{score:92,feedback:'Strong'},coach)).status,200);
 assert.equal((await request('/leaderboard','GET',undefined,coach)).status,403);
 const secondPassword=randomBytes(24).toString('hex');
 assert.equal((await request('/users','POST',{name:'Other coach',email:'second@test.invalid',role:'coach',password:secondPassword},admin)).status,201);
 const otherCoach=(await request('/login','POST',{email:'second@test.invalid',password:secondPassword})).cookie;
 assert(otherCoach);
 assert.equal((await request('/evaluations','GET',undefined,otherCoach)).data.evaluations.length,0);
 assert.equal((await request('/evaluations','GET',undefined,coach)).data.evaluations.length,1);
 const board=await request('/leaderboard','GET',undefined,admin);
 assert.equal(board.data.leaderboard[0].average_score,92);
 assert.equal(board.data.leaderboard[0].evaluation_count,1);
 assert.equal((await request('/logout','POST',{},coach)).status,200);
 assert.equal((await request('/me','GET',undefined,coach)).status,401);
 assert.equal((await request('/teams','GET',undefined,coach)).status,401);
 assert.equal((await request('/teams/'+id,'DELETE',{},otherCoach)).status,403);
 const results=await Promise.all(Array.from({length:64},()=>request('/health')));
 assert(results.every(x=>x.status===200));
});
